version: "3.9"

services:
  server1:
    build: ./server
    container_name: server1
    environment:
      - SERVER_ID=1
    networks:
      net1:
        aliases:
          - server1

  server2:
    build: ./server
    container_name: server2
    environment:
      - SERVER_ID=2
    networks:
      net1:
        aliases:
          - server2

  server3:
    build: ./server
    container_name: server3
    environment:
      - SERVER_ID=3
    networks:
      net1:
        aliases:
          - server3

  load_balancer:
    build: ./balancer
    container_name: load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Allow LB to control Docker
    privileged: true  # 👈 Required to spawn/remove containers
    networks:
      net1:
        aliases:
          - load_balancer
    depends_on:
      - server1
      - server2
      - server3

networks:
  net1:
    driver: bridge
